"""
Customer Schema Capture Verification

Purpose:
    Verify that the successful schema-capture execution created the expected
    catalog metadata for the Customer dataset.

What this script verifies:
    1. Schema capture run status.
    2. Dataset schema version.
    3. Captured dataset fields.
    4. PostgreSQL native datatype metadata.

Important:
    This script is READ-ONLY.
    It does not insert, update, or delete any metadata.
"""

from app.db.metastore import get_metastore_connection


# The capture run ID returned by the successful schema-capture execution.
CAPTURE_RUN_ID = 4

# The schema version ID returned by the successful schema-capture execution.
SCHEMA_VERSION_ID = 6


def main() -> None:
    """Verify the metadata generated by the schema capture."""

    # Open a connection to the metadata/control database.
    with get_metastore_connection() as connection:

        # ---------------------------------------------------------------
        # 1. Verify the schema capture run.
        # ---------------------------------------------------------------
        print("=" * 90)
        print("1. SCHEMA CAPTURE RUN")
        print("=" * 90)

        capture_run_query = """
            SELECT
                schema_capture_run_id,
                tenant_id,
                dataset_binding_id,
                connector_version_id,
                capture_mode_code,
                status_code,
                started_at,
                ended_at
            FROM catalog.schema_capture_run
            WHERE schema_capture_run_id = %s;
        """

        # Execute the read-only capture-run query.
        with connection.cursor() as cursor:
            cursor.execute(
                capture_run_query,
                (CAPTURE_RUN_ID,),
            )

            # Fetch the capture-run record.
            capture_run = cursor.fetchone()

        # Fail clearly if the expected record does not exist.
        if capture_run is None:
            raise LookupError(
                f"Capture run {CAPTURE_RUN_ID} was not found."
            )

        # Display the capture-run metadata.
        print(f"Capture Run ID      : {capture_run[0]}")
        print(f"Tenant ID           : {capture_run[1]}")
        print(f"Dataset Binding ID  : {capture_run[2]}")
        print(f"Connector Version   : {capture_run[3]}")
        print(f"Capture Mode        : {capture_run[4]}")
        print(f"Status              : {capture_run[5]}")
        print(f"Started At          : {capture_run[6]}")
        print(f"Ended At            : {capture_run[7]}")

        # Confirm that the capture run completed successfully.
        if capture_run[5] != "COMPLETED":
            raise RuntimeError(
                f"Capture run status is {capture_run[5]}, "
                "expected COMPLETED."
            )

        # ---------------------------------------------------------------
        # 2. Verify the schema version.
        # ---------------------------------------------------------------
        print()
        print("=" * 90)
        print("2. DATASET SCHEMA VERSION")
        print("=" * 90)

        schema_version_query = """
            SELECT
                schema_version_id,
                tenant_id,
                dataset_id,
                source_binding_id,
                schema_capture_run_id,
                version_no,
                schema_hash,
                source_code,
                change_type_code,
                is_current
            FROM catalog.dataset_schema_version
            WHERE schema_version_id = %s;
        """

        # Execute the schema-version query.
        with connection.cursor() as cursor:
            cursor.execute(
                schema_version_query,
                (SCHEMA_VERSION_ID,),
            )

            # Fetch the schema-version record.
            schema_version = cursor.fetchone()

        # Fail if the expected schema version does not exist.
        if schema_version is None:
            raise LookupError(
                f"Schema version {SCHEMA_VERSION_ID} was not found."
            )

        # Display the schema-version metadata.
        print(f"Schema Version ID   : {schema_version[0]}")
        print(f"Tenant ID            : {schema_version[1]}")
        print(f"Dataset ID           : {schema_version[2]}")
        print(f"Source Binding ID    : {schema_version[3]}")
        print(f"Capture Run ID       : {schema_version[4]}")
        print(f"Version Number       : {schema_version[5]}")
        print(f"Schema Hash          : {schema_version[6]}")
        print(f"Source Code          : {schema_version[7]}")
        print(f"Change Type          : {schema_version[8]}")
        print(f"Current Version      : {schema_version[9]}")

        # Verify that the schema version belongs to the expected capture run.
        if schema_version[4] != CAPTURE_RUN_ID:
            raise RuntimeError(
                "Schema version is not linked to the expected capture run."
            )

        # Verify that this is the current schema version.
        if schema_version[9] is not True:
            raise RuntimeError(
                "Expected Customer schema version to be marked as current."
            )

        # ---------------------------------------------------------------
        # 3. Verify the dataset fields.
        # ---------------------------------------------------------------
        print()
        print("=" * 90)
        print("3. DATASET FIELDS")
        print("=" * 90)

        fields_query = """
            SELECT
                df.field_id,
                df.ordinal_no,
                df.field_name,
                df.native_datatype_id,
                df.source_datatype_text,
                df.is_nullable,
                df.default_expression
            FROM catalog.dataset_field AS df
            WHERE df.schema_version_id = %s
            ORDER BY df.ordinal_no;
        """

        # Execute the field query.
        with connection.cursor() as cursor:
            cursor.execute(
                fields_query,
                (SCHEMA_VERSION_ID,),
            )

            # Fetch all fields belonging to this schema version.
            fields = cursor.fetchall()

        # The source table is expected to contain four columns.
        if len(fields) != 4:
            raise RuntimeError(
                f"Expected 4 dataset fields, but found {len(fields)}."
            )

        # Display each registered field.
        for field in fields:
            print(
                f"{field[1]}. "
                f"{field[2]} | "
                f"native_datatype_id={field[3]} | "
                f"type={field[4]} | "
                f"nullable={field[5]} | "
                f"default={field[6]}"
            )

        # ---------------------------------------------------------------
        # 4. Final verification.
        # ---------------------------------------------------------------
        print()
        print("=" * 90)
        print("SCHEMA CAPTURE VERIFICATION SUCCESSFUL")
        print("=" * 90)
        print("Capture Run       : VERIFIED")
        print("Schema Version    : VERIFIED")
        print("Dataset Fields    : 4")
        print("Current Version   : VERIFIED")
        print("Metadata Changes  : NONE")


# Execute the verification when this module is run directly.
if __name__ == "__main__":
    main()